require("dotenv").config();

let MONGODB_URI = process.env.MONGODB_URI;
let PORT = process.env.PORT;
let UPSTASH_REDIS_URL = process.env.UPSTASH_REDIS_URL;
let ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
let REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
let NODE_ENV = process.env.NODE_ENV;
let CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
let CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
let CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
let STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
let CLIENT_URL = process.env.CLIENT_URL;

module.exports = {
    MONGODB_URI, PORT, UPSTASH_REDIS_URL, ACCESS_TOKEN_SECRET, REFRESH_TOKEN_SECRET, NODE_ENV,
    CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, STRIPE_SECRET_KEY, CLIENT_URL
}